name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - vinorm
    - underthesea
    - streamlit
    - pandas
    - numpy
    - python-dotenv
    - azure
    - azure-cognitiveservices-speech
    - elevenlabs
    - langdetect
    - datetime
    - re
